export const THEME_CONFIG = [
	{
		id: 'neon-blue-pink',
		name: 'Neon Blue/Pink',
		uiColors: ['#00f3ff', '#ff007f'],
		isRandom: false,
		palette: {
			primary: 'hsla(195, 100%, 50%, 1)',
			mutedPrimary: 'hsla(195, 45%, 45%, 0.7)',
			secondary: 'hsla(320, 100%, 55%, 1)',
			mutedSecondary: 'hsla(320, 45%, 50%, 0.7)',
			accent: 'hsla(45, 100%, 50%, 1)',
			transparent: 'hsla(0, 0%, 0%, 0)'
		}
	},
	{
		id: 'solar-flare',
		name: 'Solar Flare',
		uiColors: ['#ffcc00', '#ff3300'],
		isRandom: false,
		palette: {
			primary: 'hsla(35, 100%, 55%, 1)',
			mutedPrimary: 'hsla(35, 50%, 40%, 0.7)',
			secondary: 'hsla(10, 100%, 50%, 1)',
			mutedSecondary: 'hsla(10, 50%, 40%, 0.7)',
			accent: 'hsla(55, 100%, 50%, 1)',
			transparent: 'hsla(0, 0%, 0%, 0)'
		}
	},
	{
		id: 'midnight-chroma',
		name: 'Midnight Chroma',
		uiColors: ['#222222', '#888888'],
		isRandom: false,
		palette: {
			primary: 'hsla(220, 20%, 65%, 1)',
			mutedPrimary: 'hsla(220, 15%, 35%, 0.7)',
			secondary: 'hsla(260, 25%, 60%, 1)',
			mutedSecondary: 'hsla(260, 20%, 35%, 0.7)',
			accent: 'hsla(0, 0%, 85%, 1)',
			transparent: 'hsla(0, 0%, 0%, 0)'
		}
	},
	{
		id: 'random-theme',
		name: 'Random Theme',
		uiColors: ['#ff00ff', '#00ffff', '#ffff00'],
		isRandom: true,
		palette: null // Dynamically generated by ThemeManager
	}
];